version: "3.9"

services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - 58000:8000
    depends_on:
      - surrealdb
      - test_surrealdb
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - 48000:8000
    volumes:
      - surrealdb:/db
    command: start --log debug --user root --pass root file:/db/todo.db
  test_surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - 48001:8000
    command: start --log debug --user root --pass root memory
  web:
    build: ./web
    volumes:
      - ./web:/app
    ports:
      - 28080:8080
    command: trunk serve --address 0.0.0.0
    depends_on:
      - api
volumes:
  surrealdb:
