version: "3.9"

services:
  api:
    build: .
    ports:
      - 58000:8000
    depends_on:
      - surrealdb
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - 48000:8000
    volumes:
      - surrealdb:/db
    command: start --log debug --user root --pass root file:/db/todo.db
volumes:
  surrealdb:
