[database]
namespace = "todo"
database = "todo"
username = "root"
password = "root"
host = "surrealdb"
port = "8000"

[test_database]
namespace = "todo"
username = "root"
password = "root"
host = "test_surrealdb"
port = "8000"

[cors]
origin = "http://localhost:28080"
